version: "3.8"

services:
  nginx:
    image: nginx:1.18.0
    container_name: nginx
    ports:
    - "80:80"
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./nginx/conf.d/:/etc/nginx/conf.d/
    extra_hosts:
    - "host.docker.internal:host-gateway"

  mosquitto:
    image: eclipse-mosquitto:2.0.11
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config/:/mosquitto/config/
      - ./mosquitto/data/:/mosquitto/data/
      - ./mosquitto/log/:/mosquitto/log/

  mysql:
    image: mysql:8.0-debian
    container_name: database
    environment:
      TZ: "Asia/Taipei"
      # - MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: "12345678"
      MYSQL_DATABASE: automeow
    volumes:
      - ./database/mysql/:/var/lib/mysql/
      - ./database/init/:/docker-entrypoint-initdb.d/
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - mysql
    environment:
      TZ: "Asia/Taipei"
      PMA_HOST: database
      PMA_PORT: 3306
    ports:
      - "9080:80"