version: "3.8"

services:
  nginx:
    image: nginx:1.18.0
    container_name: nginx
    ports:
    - "20080:80"
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  mosquitto:
    image: eclipse-mosquitto:2.0.11
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/logs:/mosquitto/log